package com.example.domain;

public class Animal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.id
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.name
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    private Integer name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.lags
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    private Integer lags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.id
     *
     * @return the value of animal.id
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.id
     *
     * @param id the value for animal.id
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.name
     *
     * @return the value of animal.name
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    public Integer getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.name
     *
     * @param name the value for animal.name
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    public void setName(Integer name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.lags
     *
     * @return the value of animal.lags
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    public Integer getLags() {
        return lags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.lags
     *
     * @param lags the value for animal.lags
     *
     * @mbggenerated Thu Mar 16 18:19:08 CST 2017
     */
    public void setLags(Integer lags) {
        this.lags = lags;
    }
}